#!/usr/bin/env node
// Generates web/src/design/tokens.css from docs/design-system/tokens.json.
//
//   npm run tokens            write the file
//   npm run tokens -- --check exit 1 if the committed file is stale
//
// Layout: House first (it doubles as :root), then one block per other theme
// with its colours and shadows, then the theme-independent scales on :root.
// Radii are emitted as --oc-radius-* because globals.css already owns
// --radius-sm/md/lg/pill with different values for the legacy pages.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, '../../docs/design-system/tokens.json');
const OUT = resolve(here, '../src/design/tokens.css');

export function generate(tokens) {
  const themes = tokens.color.themes.map((t) => t.id);
  const colour = tokens.color.tokens;
  const shadow = tokens.shadow.tokens;
  const out = [];
  out.push('/* Generated by web/scripts/gen-tokens.mjs from docs/design-system/tokens.json.');
  out.push('   Do not edit by hand: change tokens.json and run `npm run tokens`. */');
  out.push('');
  for (const theme of themes) {
    const sel = theme === 'house' ? ':root, [data-theme="house"]' : `[data-theme="${theme}"]`;
    const name = tokens.color.themes.find((t) => t.id === theme).name;
    out.push(`/* ${name} */`);
    out.push(`${sel} {`);
    for (const t of colour) {
      if (!(theme in t.value)) throw new Error(`token ${t.name} has no value for ${theme}`);
      out.push(`  --${t.name}: ${t.value[theme]};`);
    }
    for (const t of shadow) {
      if (!(theme in t.value)) throw new Error(`shadow ${t.name} has no value for ${theme}`);
      out.push(`  --${t.name}: ${t.value[theme]};`);
    }
    out.push('}');
    out.push('');
  }
  out.push('/* Scales shared by every theme */');
  out.push(':root {');
  for (const t of tokens.spacing.tokens) out.push(`  --${t.name}: ${t.value};`);
  for (const t of tokens.radius.tokens) out.push(`  --oc-${t.name}: ${t.value};`);
  for (const group of tokens.type.groups) {
    for (const s of group.styles) {
      out.push(`  --type-${s.name}-size: ${s.fontSize};`);
      out.push(`  --type-${s.name}-line: ${s.lineHeight};`);
      out.push(`  --type-${s.name}-weight: ${s.fontWeight};`);
      if (s.letterSpacing) out.push(`  --type-${s.name}-tracking: ${s.letterSpacing};`);
    }
  }
  out.push('}');
  out.push('');
  return out.join('\n');
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const css = generate(JSON.parse(readFileSync(SRC, 'utf8')));
  if (process.argv.includes('--check')) {
    let current = '';
    try { current = readFileSync(OUT, 'utf8'); } catch { /* missing */ }
    if (current !== css) {
      console.error('tokens.css is out of date. Run `npm run tokens`.');
      process.exit(1);
    }
    console.log('tokens.css is up to date.');
  } else {
    writeFileSync(OUT, css);
    console.log(`Wrote ${OUT}`);
  }
}
